### ISSUE TITLE
Módulo faltando

### ISSUE THREAD

**Issue by EnzoSimionato** [Matheus0liveira/next-level-week-3#1]
Aparentemente está faltando um arquivo no projeto (Backend) denominado 'variable'

**Comment by Matheus0liveira** [comment]
Oi, como eu tava sofrendo por não está conseguindo usar variáveis de
ambiente por conta do ts, eu criei na raiz do projeto um arquivo
variable.ts exportando os valores do token( hash e o expiresIn)

Em sex, 23 de out de 2020 21:35, Enzo Simionato <notifications@github.com>
escreveu:

**Comment by Matheus0liveira** [comment]
No Readme, na parte da instalação do backend explico como deve ser feito
